### ISSUE TITLE
Big sur reboots after 12 minutes remaining diskarbitrationd error

### ISSUE THREAD

**Issue by pavs94** [jdleung/OpenCore-Z370-P-II#2]
Cpu: i5 9600k
Mobo: asus prime z370-P ii
Ssd crucial P5 1TB Nvme formatted with MacOS Journaled GUID

I'm getting the error right at 12 minutes remaining for diskarbitrationd Sigkill having the same efi as yours.

**Comment by jdleung** [comment]
There are many reasons for the problems of a hackintosh, the repo only shows the possibility of my hardware combination, sorry you have to find out the solution of yours.
